/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Business.BuyKing;
import Business.Leilao;
import Business.Produto;
import Business.Utilizador;
import Business.Venda;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.Menu;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import javax.swing.filechooser.FileFilter;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import sun.applet.Main;

/**
 *
 * @author Pedro
 */
public class PrincipalBody extends javax.swing.JInternalFrame {

  
    /**
     * Creates new form PrincipalBody
     * Cria o kingClienteArea mal é construido
     */
   
    private KingClienteArea kingArea;
    private  BufferedImage imgProduto;
    private BuyKing sys;
    private Principal p;
   
    public PrincipalBody(BuyKing sysIn, Principal p) {
        initComponents();
       
        this.sys=sysIn;
        this.p=p;
        this.iniciarZonasEnable();
    }

    
    /**
     * O que coordena as zona que foram enable!
     */
    void iniciarZonasEnable(){
        //colocar pesqAvançada!
        pesqAvancEnable();
        if(this.p.getReg()==null)
        enableLogIn(false);
        else
        {
            enableLogIn(true);
            loadImgUser();
        }
    }
    
 /**Para os visitantes/users*/
    private void enableLogIn(boolean flag){
     enablePainel(this.MenuPrincipal,flag);
     enablePainel(this.DefUser, flag);
     enablePainel(this.jPanelMenuUser, flag);
 //enablePainel(this.jPanelSujestoes, flag);
 }
 
 /**Função genérica de enable/disable panle*/
 private static void enablePainel(JPanel panel,boolean flag){
     for(Component elem: panel.getComponents()){
     elem.setEnabled(flag);
     }
 }
    
    /**Get do king Area*/
    public KingClienteArea getKingArea(){
        return this.kingArea;
       
    }
     
    
    public BufferedImage getImgProduto(){
    return this.imgProduto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
      
    /**Cria nova janela Area do cliente faz o get do Desktop Pane*/
    public void abreJanelaAreaCliente()
    { 
    try {   
        
        
            if(p.getReg()!=null)
            {
                this.kingArea=new KingClienteArea(this.p.getReg(), this.sys);
                this.getDesktopPane().add(this.kingArea);
                this.kingArea.setVisible(true);
                this.kingArea.setSelected(true);
            }
            else{
                JOptionPane.showInternalMessageDialog(this, "Efectue o logIn para aceder à KingArea", "Efectue LogIn", JOptionPane.ERROR_MESSAGE);
            }
        } catch (PropertyVetoException ex) 
        {
            Logger.getLogger(PrincipalBody.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException e){
            JOptionPane.showInternalMessageDialog(this, e, "Erro ao aceder ao servidor",JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /*Abre janela de escolher Imagem de produto:Limpar a imagem antrior!*/
    public void abreFileChooser() {
        JFileChooser file = new JFileChooser();
        FileFilter ff=  new ExtensionFileFilter("JPG and JPEG", new String[] { "JPG", "JPEG" });
        file.setFileFilter(ff);
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showSaveDialog(null);

        if (i == 1) {
            //JOptionPane.showMessageDialog(null, "Procurar Localidade Erro:\n Não existe Localidade", "Erro", JOptionPane.ERROR_MESSAGE);

        } else {
            
            
            File arquivo = file.getSelectedFile();
            try {
                    this.imgProduto=ImageIO.read(arquivo);
                    loadImgProd();
                } 
                catch (IOException ex)
                {
                    //Erro carregar Imagem!
                     Logger.getLogger(PrincipalBody.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
    }
    
    
    //Desactivar/Act a parte de pesquisa avançada
    public void pesqAvancEnable(){
    
        boolean flag=false;       
        if(this.jCheckBoxActivaFiltro.isSelected())
            flag=true;
             
        for(Component elem:this.jPanelVLeilao.getComponents()){
            elem.setEnabled(flag);
        }
    }
    
    
    /**
     * Carraga Imagens de um produto!
     */
    
    public void loadImgProd()
    {
       int lar= this.jPanelAddImagem.getWidth();
        int alt=this.jPanelAddImagem.getHeight();     
        
        Image resizedImage = this.imgProduto.getScaledInstance(lar-10,alt-10, Image.SCALE_DEFAULT);
        
        ImageIcon icon = new ImageIcon(resizedImage);
        this.jLabelImagemProd.setIcon(icon);
    
    }
    
    
    
    /**
     * Carrega o avatar do user caso tenha feito o logIn
    */
    public void loadImgUser()
    {
        if(this.p.getReg().getImagem()!=null)
        {
            int lar= this.jScrollPaneImgUser.getWidth();
            int alt=this.jScrollPaneImgUser.getHeight();     
        
            Image resizedImage = this.p.getReg().getImagem().getScaledInstance(lar-10,alt-10, Image.SCALE_DEFAULT);
        
        ImageIcon icon = new ImageIcon(resizedImage);
        this.jLabel3.setIcon(icon);
        }
    
    }
    
    
    
    /**
     * Pesquisa/Muda de painel pesquisa.
     */
    public void pesquisarKey() {
        //Actividade do card layout
        CardLayout card = (CardLayout) this.BodyPrincipal.getLayout();
        card.show(this.BodyPrincipal, "cardPesquisa");
        // TODO add your handling code here:
        //Todas
        //Venda
        //Leilão
        try {
            String[] nomesCol = {"Nome", "Preço", "Tipo"};
            DefaultTableModel m = new DefaultTableModel(nomesCol, 0);
            jTableResultadosPesquisa.setModel(m);
            m.fireTableDataChanged();
            List<Venda> vendas;
            List<Leilao> leiloes;
            if (this.jCheckBoxActivaFiltro.isSelected()) {
                if (jComboBoxTransacao.getSelectedItem().equals("Todas")
                        || jComboBoxTransacao.getSelectedItem().equals("Venda")) {
                    vendas = sys.pesquisaVendasAvançada(ChavePesquisa.getText(),
                            (String) jComboBoxCategoria.getSelectedItem(),
                            Float.parseFloat(jTextField1.getText()), Float.parseFloat(jTextField2.getText()));
                    for (Venda v : vendas) {
                        Object[] line = {v.getProduto().getNome(), v.getPreco(), "Venda"};
                        m.addRow(line);
                    }
                }
                if (jComboBoxTransacao.getSelectedItem().equals("Todas")
                        || jComboBoxTransacao.getSelectedItem().equals("Leilão")) {
                    leiloes = sys.pesquisaAvançadaLeilao(ChavePesquisa.getText(),
                            (String) jComboBoxCategoria.getSelectedItem(),
                            Float.parseFloat(jTextField1.getText()), Float.parseFloat(jTextField2.getText()));
                    for (Leilao l : leiloes) {
                        Object[] line = {l.getP().getNome(), l.getUltimaLicitacao(), "Leilão"};
                        m.addRow(line);
                    }
                }
            } else {
                if (jComboBoxTransacao.getSelectedItem().equals("Todas")
                        || jComboBoxTransacao.getSelectedItem().equals("Venda")) {
                    vendas = sys.pesquisaVendasSimples(ChavePesquisa.getText(),
                            (String) jComboBoxCategoria.getSelectedItem());
                    for (Venda v : vendas) {
                        Object[] line = {v.getProduto().getNome(), v.getPreco(), "Venda"};
                        m.addRow(line);
                    }
                }
                if (jComboBoxTransacao.getSelectedItem().equals("Todas")
                        || jComboBoxTransacao.getSelectedItem().equals("Venda")) {
                    leiloes = sys.pesquisaSimplesLeilao(ChavePesquisa.getText(),
                            (String) jComboBoxCategoria.getSelectedItem());
                    for (Leilao l : leiloes) {
                        Object[] line = {l.getP().getNome(), l.getUltimaLicitacao(), "Leilão"};
                        m.addRow(line);
                    }
                }
            }
            m.fireTableDataChanged();
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(this, e, "Erro ocorrido durante a pesquisa.", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logotipo = new javax.swing.JPanel();
        jLabelLogoTipo = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JPanel();
        jButtonVender = new javax.swing.JButton();
        jButtonLeiloar = new javax.swing.JButton();
        jButtonMenuFavoritos = new javax.swing.JButton();
        jPanelPesquisa = new javax.swing.JPanel();
        jLabelPesq = new javax.swing.JLabel();
        ChavePesquisa = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jButtonPesquisar = new javax.swing.JButton();
        DefUser = new javax.swing.JPanel();
        jPanelMenuUser = new javax.swing.JPanel();
        jButtonKingArea = new javax.swing.JButton();
        jButtonAjuda = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPaneImgUser = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jPanelPesquisaAvanc = new javax.swing.JPanel();
        jComboBoxTransacao = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxActivaFiltro = new javax.swing.JCheckBox();
        jPanelVLeilao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        BodyPrincipal = new javax.swing.JPanel();
        PanelPesq = new javax.swing.JPanel();
        jScrollResultadosPesquisa = new javax.swing.JScrollPane();
        jTableResultadosPesquisa = new javax.swing.JTable();
        ProdutoCompra = new javax.swing.JPanel();
        jPanelImagem = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelDescricao = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabelcontacto = new javax.swing.JLabel();
        jButtonfavorit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelpreco2 = new javax.swing.JLabel();
        jLabelvalor = new javax.swing.JLabel();
        jButtoncomprar = new javax.swing.JButton();
        jButtontrocar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ProdutoEmLeilao = new javax.swing.JPanel();
        jScrollPaneImagemProduto = new javax.swing.JScrollPane();
        jLabel19 = new javax.swing.JLabel();
        jPanelDescricaoProduto = new javax.swing.JPanel();
        jLabelLicitarNomeP = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaLicitarDesc = new javax.swing.JTextArea();
        jLabelEmail = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButtonfavorit1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabelValorBase = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabelTectoValor = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelDataLeilao = new javax.swing.JLabel();
        jTextFieldNovaLicitacao = new javax.swing.JTextField();
        jButtonLicitar = new javax.swing.JButton();
        jButtonComprarTecto = new javax.swing.JButton();
        jComboBoxClassif = new javax.swing.JComboBox();
        jButtonGoBack = new javax.swing.JButton();
        Vender = new javax.swing.JPanel();
        jPanelAddImagem = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabelImagemProd = new javax.swing.JLabel();
        JpanelPropriedadesProduto = new javax.swing.JPanel();
        lnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLdescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jComboBoxCategoria1 = new javax.swing.JComboBox();
        jLabelpreco = new javax.swing.JLabel();
        jTexpreco = new javax.swing.JTextField();
        jLabelEuro = new javax.swing.JLabel();
        jButtonvend = new javax.swing.JButton();
        jBcimagem = new javax.swing.JButton();
        Favoritos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonFavProduto = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        logotipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelLogoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FinalLog128.png"))); // NOI18N

        javax.swing.GroupLayout logotipoLayout = new javax.swing.GroupLayout(logotipo);
        logotipo.setLayout(logotipoLayout);
        logotipoLayout.setHorizontalGroup(
            logotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logotipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logotipoLayout.setVerticalGroup(
            logotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logotipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelLogoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        MenuPrincipal.setName("Produtos"); // NOI18N

        jButtonVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ColocarVender.png"))); // NOI18N
        jButtonVender.setText("Vender");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });

        jButtonLeiloar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ColocarEmLeilão.png"))); // NOI18N
        jButtonLeiloar.setText("Leiloar");
        jButtonLeiloar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeiloarActionPerformed(evt);
            }
        });

        jButtonMenuFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lixo.png"))); // NOI18N
        jButtonMenuFavoritos.setText("Favoritos");
        jButtonMenuFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuFavoritosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMenuFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jButtonLeiloar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jButtonVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addComponent(jButtonVender, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jButtonLeiloar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMenuFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPesq.setText("Pesquisa:");

        ChavePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChavePesquisaActionPerformed(evt);
            }
        });

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<html><strong>Categoria</strong></html>", "Moda", "Tecnologia", "Moveis", "Casa e Jardim", "Lazer", "Desporto", "Imoveis", "Emprego", "Carros", "Motos", "Barcos", "Animais", "Serviços", "Outros" }));
        jComboBoxCategoria.setToolTipText("");

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPesq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChavePesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaLayout.createSequentialGroup()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisar))
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChavePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );

        DefUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        DefUser.setName("Definições de Utilizador"); // NOI18N

        jPanelMenuUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Menu do User ")));

        jButtonKingArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/KingArea.png"))); // NOI18N
        jButtonKingArea.setText("King Area");
        jButtonKingArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKingAreaActionPerformed(evt);
            }
        });

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Help.png"))); // NOI18N
        jButtonAjuda.setText("Ajuda          ");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Loginicon.png"))); // NOI18N
        jButtonSair.setText(" Sair            ");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuUserLayout = new javax.swing.GroupLayout(jPanelMenuUser);
        jPanelMenuUser.setLayout(jPanelMenuUserLayout);
        jPanelMenuUserLayout.setHorizontalGroup(
            jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuUserLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKingArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuUserLayout.setVerticalGroup(
            jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuUserLayout.createSequentialGroup()
                .addComponent(jButtonKingArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/kingAvatar.png"))); // NOI18N
        jScrollPaneImgUser.setViewportView(jLabel3);

        javax.swing.GroupLayout DefUserLayout = new javax.swing.GroupLayout(DefUser);
        DefUser.setLayout(DefUserLayout);
        DefUserLayout.setHorizontalGroup(
            DefUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelMenuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DefUserLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPaneImgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DefUserLayout.setVerticalGroup(
            DefUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefUserLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPaneImgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMenuUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPesquisaAvanc.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Avançada"));

        jComboBoxTransacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Venda", "Leilão" }));
        jComboBoxTransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTransacaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de Transação :");

        jCheckBoxActivaFiltro.setText("Activar Filtro");
        jCheckBoxActivaFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActivaFiltroActionPerformed(evt);
            }
        });

        jPanelVLeilao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Preço de:");

        jTextField1.setText("0,00");

        jTextField2.setText("0.00");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel30.setText("Até:");

        jLabel31.setText("€");

        jLabel32.setText("€");

        javax.swing.GroupLayout jPanelVLeilaoLayout = new javax.swing.GroupLayout(jPanelVLeilao);
        jPanelVLeilao.setLayout(jPanelVLeilaoLayout);
        jPanelVLeilaoLayout.setHorizontalGroup(
            jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVLeilaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVLeilaoLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVLeilaoLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelVLeilaoLayout.setVerticalGroup(
            jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVLeilaoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPesquisaAvancLayout = new javax.swing.GroupLayout(jPanelPesquisaAvanc);
        jPanelPesquisaAvanc.setLayout(jPanelPesquisaAvancLayout);
        jPanelPesquisaAvancLayout.setHorizontalGroup(
            jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaAvancLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesquisaAvancLayout.createSequentialGroup()
                        .addComponent(jCheckBoxActivaFiltro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaAvancLayout.createSequentialGroup()
                        .addGroup(jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaAvancLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTransacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaAvancLayout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(jPanelVLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanelPesquisaAvancLayout.setVerticalGroup(
            jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaAvancLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxActivaFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelVLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        BodyPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BodyPrincipal.setPreferredSize(new java.awt.Dimension(400, 400));
        BodyPrincipal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                BodyPrincipalComponentAdded(evt);
            }
        });
        BodyPrincipal.setLayout(new java.awt.CardLayout());

        PanelPesq.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));
        PanelPesq.setToolTipText("");

        jTableResultadosPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollResultadosPesquisa.setViewportView(jTableResultadosPesquisa);

        javax.swing.GroupLayout PanelPesqLayout = new javax.swing.GroupLayout(PanelPesq);
        PanelPesq.setLayout(PanelPesqLayout);
        PanelPesqLayout.setHorizontalGroup(
            PanelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPesqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollResultadosPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPesqLayout.setVerticalGroup(
            PanelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPesqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollResultadosPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addGap(218, 218, 218))
        );

        BodyPrincipal.add(PanelPesq, "cardPesquisa");

        jPanelImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Foto");

        javax.swing.GroupLayout jPanelImagemLayout = new javax.swing.GroupLayout(jPanelImagem);
        jPanelImagem.setLayout(jPanelImagemLayout);
        jPanelImagemLayout.setHorizontalGroup(
            jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelImagemLayout.setVerticalGroup(
            jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDescricao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDescricao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Nome");
        jPanelDescricao.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel13.setText("Descrição :");
        jPanelDescricao.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jScrollPane7.setViewportView(jEditorPane1);

        jPanelDescricao.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 110));

        jLabelcontacto.setText("Contacto do Vendedor");

        jButtonfavorit.setText("Adicionar aos Favoritos");

        jLabel15.setText("Classificação do Vendedor(0 a 5)");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelpreco2.setText("Preço :");

        jLabelvalor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelvalor.setText("Valor(€€€€)");

        jButtoncomprar.setText("Comprar");

        jButtontrocar.setText("Propor Troca");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelpreco2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtoncomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtontrocar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtontrocar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos vendedor "));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProdutoCompraLayout = new javax.swing.GroupLayout(ProdutoCompra);
        ProdutoCompra.setLayout(ProdutoCompraLayout);
        ProdutoCompraLayout.setHorizontalGroup(
            ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonfavorit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        ProdutoCompraLayout.setVerticalGroup(
            ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addComponent(jPanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelcontacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonfavorit))
                    .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BodyPrincipal.add(ProdutoCompra, "ProdutoCompra");

        ProdutoEmLeilao.setPreferredSize(new java.awt.Dimension(426, 400));

        jLabel19.setText("asdasdasd");
        jScrollPaneImagemProduto.setViewportView(jLabel19);

        jPanelDescricaoProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabelLicitarNomeP.setText("Nome");

        jLabel21.setText("Descrição :");

        jTextAreaLicitarDesc.setColumns(20);
        jTextAreaLicitarDesc.setEditable(false);
        jTextAreaLicitarDesc.setRows(5);
        jScrollPane6.setViewportView(jTextAreaLicitarDesc);

        jLabelEmail.setText("Email do vendedor");

        javax.swing.GroupLayout jPanelDescricaoProdutoLayout = new javax.swing.GroupLayout(jPanelDescricaoProduto);
        jPanelDescricaoProduto.setLayout(jPanelDescricaoProdutoLayout);
        jPanelDescricaoProdutoLayout.setHorizontalGroup(
            jPanelDescricaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoProdutoLayout.createSequentialGroup()
                .addGroup(jPanelDescricaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDescricaoProdutoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelLicitarNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDescricaoProdutoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel21))
                    .addGroup(jPanelDescricaoProdutoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDescricaoProdutoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanelDescricaoProdutoLayout.setVerticalGroup(
            jPanelDescricaoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoProdutoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelLicitarNomeP)
                .addGap(2, 2, 2)
                .addComponent(jLabel21)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel22.setText("Classificação do Vendedor(0 a 5)");

        jButtonfavorit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lixo.png"))); // NOI18N
        jButtonfavorit1.setText("Adicionar aos Favoritos");

        jLabel24.setText("Licitação Atual:");

        jLabelValorBase.setText("€€€€");

        jLabel26.setText("Teto de licitação: ");

        jLabelTectoValor.setText("€€€€");

        jLabel28.setText("Data do Fim do Leilão:");

        jLabelDataLeilao.setText("aaaa/mm/dd    hh:mm");

        jTextFieldNovaLicitacao.setText("valorALicitar");
        jTextFieldNovaLicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNovaLicitacaoActionPerformed(evt);
            }
        });

        jButtonLicitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Leilão.png"))); // NOI18N
        jButtonLicitar.setText("Licitar");

        jButtonComprarTecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Moneyicon.png"))); // NOI18N
        jButtonComprarTecto.setText("Compro Já");

        jComboBoxClassif.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        jButtonGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/goback.png"))); // NOI18N

        javax.swing.GroupLayout ProdutoEmLeilaoLayout = new javax.swing.GroupLayout(ProdutoEmLeilao);
        ProdutoEmLeilao.setLayout(ProdutoEmLeilaoLayout);
        ProdutoEmLeilaoLayout.setHorizontalGroup(
            ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdutoEmLeilaoLayout.createSequentialGroup()
                .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNovaLicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxClassif, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel22))))
                    .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                        .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDataLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonfavorit1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPaneImagemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jPanelDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabelTectoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonComprarTecto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProdutoEmLeilaoLayout.setVerticalGroup(
            ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanelDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProdutoEmLeilaoLayout.createSequentialGroup()
                        .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPaneImagemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonfavorit1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataLeilao)
                            .addComponent(jLabel28))))
                .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(2, 2, 2)
                        .addComponent(jComboBoxClassif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProdutoEmLeilaoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabelValorBase)
                            .addComponent(jTextFieldNovaLicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProdutoEmLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabelTectoValor)
                            .addComponent(jButtonComprarTecto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        this.jComboBoxClassif.setToolTipText("Classificar utilizador.");
        this.jButtonGoBack.setToolTipText("Voltar à pesquisa");

        BodyPrincipal.add(ProdutoEmLeilao, "cardLicitar");

        Vender.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanelAddImagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));
        jPanelAddImagem.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jLabelImagemProd);

        jPanelAddImagem.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        JpanelPropriedadesProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));
        JpanelPropriedadesProduto.setMaximumSize(new java.awt.Dimension(195, 370));
        JpanelPropriedadesProduto.setPreferredSize(new java.awt.Dimension(195, 370));

        lnome.setText("Nome produto :");

        jTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeActionPerformed(evt);
            }
        });

        jLdescricao.setText("Descrição:");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jComboBoxCategoria1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<html><strong>Categoria</strong></html>", "Moda", "Tecnologia", "Moveis", "Casa e Jardim", "Lazer", "Desporto", "Imoveis", "Emprego", "Carros", "Motos", "Barcos", "Animais", "Serviços", "Outros" }));
        jComboBoxCategoria1.setToolTipText("");
        jComboBoxCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoria1ActionPerformed(evt);
            }
        });

        jLabelpreco.setText("Preço:");

        jLabelEuro.setText("€");

        jButtonvend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ColocarVender.png"))); // NOI18N
        jButtonvend.setText("Colocar à venda");
        jButtonvend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelPropriedadesProdutoLayout = new javax.swing.GroupLayout(JpanelPropriedadesProduto);
        JpanelPropriedadesProduto.setLayout(JpanelPropriedadesProdutoLayout);
        JpanelPropriedadesProdutoLayout.setHorizontalGroup(
            JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                .addGroup(JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLdescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                        .addGroup(JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                                .addComponent(lnome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelpreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonvend)
                                    .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                                        .addComponent(jTexpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JpanelPropriedadesProdutoLayout.setVerticalGroup(
            JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnome)
                    .addComponent(jTnome))
                .addGap(9, 9, 9)
                .addComponent(jComboBoxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTexpreco)
                    .addComponent(jLabelpreco)
                    .addComponent(jLabelEuro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonvend, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jBcimagem.setText("Carregar Imagem");
        jBcimagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcimagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VenderLayout = new javax.swing.GroupLayout(Vender);
        Vender.setLayout(VenderLayout);
        VenderLayout.setHorizontalGroup(
            VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenderLayout.createSequentialGroup()
                .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VenderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanelAddImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VenderLayout.createSequentialGroup()
                        .addContainerGap(122, Short.MAX_VALUE)
                        .addComponent(jBcimagem)
                        .addGap(21, 21, 21)))
                .addGap(18, 18, 18)
                .addComponent(JpanelPropriedadesProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
        VenderLayout.setVerticalGroup(
            VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenderLayout.createSequentialGroup()
                .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VenderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelAddImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBcimagem))
                    .addGroup(VenderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JpanelPropriedadesProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        BodyPrincipal.add(Vender, "cardVender");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButtonFavProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/file.png"))); // NOI18N
        jButtonFavProduto.setText("Ver Produto");

        javax.swing.GroupLayout FavoritosLayout = new javax.swing.GroupLayout(Favoritos);
        Favoritos.setLayout(FavoritosLayout);
        FavoritosLayout.setHorizontalGroup(
            FavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FavoritosLayout.createSequentialGroup()
                .addGroup(FavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FavoritosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FavoritosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFavProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        FavoritosLayout.setVerticalGroup(
            FavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FavoritosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jButtonFavProduto)
                .addGap(46, 46, 46))
        );

        BodyPrincipal.add(Favoritos, "cardFavoritos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPesquisaAvanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DefUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(253, 253, 253)
                    .addComponent(BodyPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGap(240, 240, 240)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DefUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logotipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanelPesquisaAvanc, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(157, Short.MAX_VALUE)
                    .addComponent(BodyPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed
      CardLayout card =(CardLayout) this.BodyPrincipal.getLayout();
      card.show(this.BodyPrincipal,"cardVender");
    }//GEN-LAST:event_jButtonVenderActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldNovaLicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNovaLicitacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNovaLicitacaoActionPerformed

    private void ChavePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChavePesquisaActionPerformed
        pesquisarKey();
    }//GEN-LAST:event_ChavePesquisaActionPerformed

    private void BodyPrincipalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_BodyPrincipalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyPrincipalComponentAdded

    private void jComboBoxTransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTransacaoActionPerformed

    }//GEN-LAST:event_jComboBoxTransacaoActionPerformed

    private void jTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeActionPerformed

    private void jButtonKingAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKingAreaActionPerformed
       abreJanelaAreaCliente();
    }//GEN-LAST:event_jButtonKingAreaActionPerformed

    private void jBcimagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcimagemActionPerformed
       abreFileChooser();  
    }//GEN-LAST:event_jBcimagemActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBoxActivaFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActivaFiltroActionPerformed
    pesqAvancEnable();
    }//GEN-LAST:event_jCheckBoxActivaFiltroActionPerformed

    private void jComboBoxCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoria1ActionPerformed

    private void jButtonvendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvendActionPerformed
        try {
            Produto pr=sys.addProduto(p.getReg(), this.jTnome.getText(), this.imgProduto, this.jTextAreaDescricao.getText(), (String) this.jComboBoxCategoria1.getSelectedItem());
            if(pr!=null){
                if(sys.vender(p.getReg(),pr, Float.parseFloat(jTexpreco.getText())));
                else{
                    //TODO
                }
            }
            else{
                //TODO
            }
        }catch(Exception e){System.err.println(e);
            }
        
    }//GEN-LAST:event_jButtonvendActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
   pesquisarKey();
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        //deActiva  Zona de cliente!
        iniciarZonasEnable();        
    }//GEN-LAST:event_formFocusGained

    private void jButtonLeiloarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeiloarActionPerformed
        CardLayout card =(CardLayout) this.BodyPrincipal.getLayout();
      card.show(this.BodyPrincipal,"cardLicitar");
    }//GEN-LAST:event_jButtonLeiloarActionPerformed

    private void jButtonMenuFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuFavoritosActionPerformed
          CardLayout card =(CardLayout) this.BodyPrincipal.getLayout();
      card.show(this.BodyPrincipal,"cardFavoritos");
    }//GEN-LAST:event_jButtonMenuFavoritosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPrincipal;
    private javax.swing.JTextField ChavePesquisa;
    private javax.swing.JPanel DefUser;
    private javax.swing.JPanel Favoritos;
    private javax.swing.JPanel JpanelPropriedadesProduto;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel PanelPesq;
    private javax.swing.JPanel ProdutoCompra;
    private javax.swing.JPanel ProdutoEmLeilao;
    private javax.swing.JPanel Vender;
    private javax.swing.JButton jBcimagem;
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonComprarTecto;
    private javax.swing.JButton jButtonFavProduto;
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JButton jButtonKingArea;
    private javax.swing.JButton jButtonLeiloar;
    private javax.swing.JButton jButtonLicitar;
    private javax.swing.JButton jButtonMenuFavoritos;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JButton jButtoncomprar;
    private javax.swing.JButton jButtonfavorit;
    private javax.swing.JButton jButtonfavorit1;
    private javax.swing.JButton jButtontrocar;
    private javax.swing.JButton jButtonvend;
    private javax.swing.JCheckBox jCheckBoxActivaFiltro;
    private javax.swing.JComboBox jComboBoxCategoria;
    private javax.swing.JComboBox jComboBoxCategoria1;
    private javax.swing.JComboBox jComboBoxClassif;
    private javax.swing.JComboBox jComboBoxTransacao;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDataLeilao;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEuro;
    private javax.swing.JLabel jLabelImagemProd;
    private javax.swing.JLabel jLabelLicitarNomeP;
    private javax.swing.JLabel jLabelLogoTipo;
    private javax.swing.JLabel jLabelPesq;
    private javax.swing.JLabel jLabelTectoValor;
    private javax.swing.JLabel jLabelValorBase;
    private javax.swing.JLabel jLabelcontacto;
    private javax.swing.JLabel jLabelpreco;
    private javax.swing.JLabel jLabelpreco2;
    private javax.swing.JLabel jLabelvalor;
    private javax.swing.JLabel jLdescricao;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAddImagem;
    private javax.swing.JPanel jPanelDescricao;
    private javax.swing.JPanel jPanelDescricaoProduto;
    private javax.swing.JPanel jPanelImagem;
    private javax.swing.JPanel jPanelMenuUser;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JPanel jPanelPesquisaAvanc;
    private javax.swing.JPanel jPanelVLeilao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPaneImagemProduto;
    private javax.swing.JScrollPane jScrollPaneImgUser;
    private javax.swing.JScrollPane jScrollResultadosPesquisa;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableResultadosPesquisa;
    private javax.swing.JTextField jTexpreco;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextArea jTextAreaLicitarDesc;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldNovaLicitacao;
    private javax.swing.JTextField jTnome;
    private javax.swing.JLabel lnome;
    private javax.swing.JPanel logotipo;
    // End of variables declaration//GEN-END:variables
   
}
