/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Business.BuyKing;
import Business.Produto;
import Business.Utilizador;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.Menu;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import javax.swing.filechooser.FileFilter;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import sun.applet.Main;

/**
 *
 * @author Pedro
 */
public class PrincipalBody extends javax.swing.JInternalFrame {

  
    /**
     * Creates new form PrincipalBody
     * Cria o kingClienteArea mal é construido
     */
   
    private KingClienteArea kingArea;
    private  BufferedImage imgProduto;
    private BuyKing sys;
    private Principal p;
   
    public PrincipalBody(BuyKing sysIn, Principal p) {
        initComponents();
        this.sys=sysIn;
        this.iniciarZonasEnable();
        this.p=p;
    }

    
    /**
     * O que coordena as zona que foram enable!
     */
    private void iniciarZonasEnable(){
        //colocar pesqAvançada!
        pesqAvancEnable();
    }
    

    
    /**Get do king Area*/
    public KingClienteArea getKingArea(){
        return this.kingArea;
       
    }
     
    
    public BufferedImage getImgProduto(){
    return this.imgProduto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
      
    /**Cria nova janela Area do cliente faz o get do Desktop Pane*/
    public void abreJanelaAreaCliente()
    { 
    try {   
        
        if(this.kingArea==null)
            this.kingArea=new KingClienteArea();
            
            this.getDesktopPane().add(this.kingArea);
            this.kingArea.setVisible(true);
            this.kingArea.setSelected(true);
        } catch (PropertyVetoException ex) 
        {
            Logger.getLogger(PrincipalBody.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /*Abre janela de escolher Imagem de produto:Limpar a imagem antrior!*/
    public void abreFileChooser() {
        JFileChooser file = new JFileChooser();
        FileFilter ff=  new ExtensionFileFilter("JPG and JPEG", new String[] { "JPG", "JPEG" });
        file.setFileFilter(ff);
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showSaveDialog(null);

        if (i == 1) {
            //JOptionPane.showMessageDialog(null, "Procurar Localidade Erro:\n Não existe Localidade", "Erro", JOptionPane.ERROR_MESSAGE);

        } else {
            
            
            File arquivo = file.getSelectedFile();
            try {
                    this.imgProduto=ImageIO.read(arquivo);
                    loadImgProd();
                } 
                catch (IOException ex)
                {
                    //Erro carregar Imagem!
                     Logger.getLogger(PrincipalBody.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
    }
    
    
    //Desactivar/Act a parte de pesquisa avançada
    public void pesqAvancEnable(){
    
        boolean flag=false;       
        if(this.jCheckBoxActivaFiltro.isSelected())
            flag=true;
             
        for(Component elem:this.jPanelVLeilao.getComponents()){
            elem.setEnabled(flag);
        }
    }
    
    
    public void loadImgProd()
    {
       int lar= this.jPanelAddImagem.getWidth();
        int alt=this.jPanelAddImagem.getHeight();     
        
        Image resizedImage = this.imgProduto.getScaledInstance(lar-10,alt-10, Image.SCALE_DEFAULT);
        
        ImageIcon icon = new ImageIcon(resizedImage);
        this.jLabelImagemProd.setIcon(icon);
    
    }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logotipo = new javax.swing.JPanel();
        jLabelLogoTipo = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JPanel();
        jButtonVender = new javax.swing.JButton();
        jButtonLeiloar = new javax.swing.JButton();
        jButtonMenuFavoritos = new javax.swing.JButton();
        jPanelPesquisa = new javax.swing.JPanel();
        jLabelPesq = new javax.swing.JLabel();
        ChavePesquisa = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jButtonPesquisar = new javax.swing.JButton();
        DefUser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelMenuUser = new javax.swing.JPanel();
        jButtonKingArea = new javax.swing.JButton();
        jButtonAjuda = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        BodyPrincipal = new javax.swing.JPanel();
        PanelPesq = new javax.swing.JPanel();
        jButtonPesqAvan = new javax.swing.JButton();
        jButtonResults = new javax.swing.JButton();
        jScrollResultadosPesquisa = new javax.swing.JScrollPane();
        jTableResultadosPesquisa = new javax.swing.JTable();
        ProdutoCompra = new javax.swing.JPanel();
        jPanelImagem = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelDescricao = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabelcontacto = new javax.swing.JLabel();
        jButtonfavorit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelpreco2 = new javax.swing.JLabel();
        jLabelvalor = new javax.swing.JLabel();
        jButtoncomprar = new javax.swing.JButton();
        jButtontrocar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ProdutoEmLeilao = new javax.swing.JPanel();
        jPanelImagemLeilao = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanelDescricaoProduto = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelcontacto1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButtonfavorit1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Vender = new javax.swing.JPanel();
        jPanelAddImagem = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabelImagemProd = new javax.swing.JLabel();
        JpanelPropriedadesProduto = new javax.swing.JPanel();
        lnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLdescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jComboBoxCategoria1 = new javax.swing.JComboBox();
        jLabelpreco = new javax.swing.JLabel();
        jTexpreco = new javax.swing.JTextField();
        jButtonvend = new javax.swing.JButton();
        jLabelEuro = new javax.swing.JLabel();
        jBcimagem = new javax.swing.JButton();
        jPanelPesquisaAvanc = new javax.swing.JPanel();
        jComboBoxTransacao = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxActivaFiltro = new javax.swing.JCheckBox();
        jPanelVLeilao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);

        logotipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelLogoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FinalLog128.png"))); // NOI18N

        javax.swing.GroupLayout logotipoLayout = new javax.swing.GroupLayout(logotipo);
        logotipo.setLayout(logotipoLayout);
        logotipoLayout.setHorizontalGroup(
            logotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logotipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logotipoLayout.setVerticalGroup(
            logotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logotipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelLogoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        MenuPrincipal.setName("Produtos"); // NOI18N

        jButtonVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ColocarVender.png"))); // NOI18N
        jButtonVender.setText("Vender");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });

        jButtonLeiloar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ColocarEmLeilão.png"))); // NOI18N
        jButtonLeiloar.setText("Leiloar");

        jButtonMenuFavoritos.setText("Favoritos");

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMenuFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jButtonLeiloar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jButtonVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addComponent(jButtonVender, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jButtonLeiloar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMenuFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPesq.setText("Pesquisa:");

        ChavePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChavePesquisaActionPerformed(evt);
            }
        });

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<html><strong>Categoria</strong></html>", "Moda", "Tecnologia", "Moveis", "Casa e Jardim", "Lazer", "Desporto", "Imoveis", "Emprego", "Carros", "Motos", "Barcos", "Animais", "Serviços", "Outros" }));
        jComboBoxCategoria.setToolTipText("");

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPesq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChavePesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaLayout.createSequentialGroup()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisar))
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChavePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );

        DefUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        DefUser.setName("Definições de Utilizador"); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/kingAvatar.png"))); // NOI18N

        jPanelMenuUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Menu do User ")));

        jButtonKingArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/KingArea.png"))); // NOI18N
        jButtonKingArea.setText("King Area");
        jButtonKingArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKingAreaActionPerformed(evt);
            }
        });

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Help.png"))); // NOI18N
        jButtonAjuda.setText("Ajuda          ");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Loginicon.png"))); // NOI18N
        jButtonSair.setText(" Sair            ");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuUserLayout = new javax.swing.GroupLayout(jPanelMenuUser);
        jPanelMenuUser.setLayout(jPanelMenuUserLayout);
        jPanelMenuUserLayout.setHorizontalGroup(
            jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuUserLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKingArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuUserLayout.setVerticalGroup(
            jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuUserLayout.createSequentialGroup()
                .addComponent(jButtonKingArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DefUserLayout = new javax.swing.GroupLayout(DefUser);
        DefUser.setLayout(DefUserLayout);
        DefUserLayout.setHorizontalGroup(
            DefUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelMenuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        DefUserLayout.setVerticalGroup(
            DefUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMenuUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BodyPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BodyPrincipal.setPreferredSize(new java.awt.Dimension(400, 400));
        BodyPrincipal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                BodyPrincipalComponentAdded(evt);
            }
        });
        BodyPrincipal.setLayout(new java.awt.CardLayout());

        PanelPesq.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));
        PanelPesq.setToolTipText("");

        jButtonPesqAvan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N
        jButtonPesqAvan.setText("Pesquisa Avançada");

        jButtonResults.setText("Mais Resultados");

        jTableResultadosPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollResultadosPesquisa.setViewportView(jTableResultadosPesquisa);

        javax.swing.GroupLayout PanelPesqLayout = new javax.swing.GroupLayout(PanelPesq);
        PanelPesq.setLayout(PanelPesqLayout);
        PanelPesqLayout.setHorizontalGroup(
            PanelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPesqLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonResults, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonPesqAvan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(PanelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelPesqLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollResultadosPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PanelPesqLayout.setVerticalGroup(
            PanelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPesqLayout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(PanelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesqAvan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(169, 169, 169))
            .addGroup(PanelPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelPesqLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollResultadosPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGap(218, 218, 218)))
        );

        BodyPrincipal.add(PanelPesq, "card7");

        jPanelImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Foto");

        javax.swing.GroupLayout jPanelImagemLayout = new javax.swing.GroupLayout(jPanelImagem);
        jPanelImagem.setLayout(jPanelImagemLayout);
        jPanelImagemLayout.setHorizontalGroup(
            jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelImagemLayout.setVerticalGroup(
            jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDescricao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDescricao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Nome");
        jPanelDescricao.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel13.setText("Descrição :");
        jPanelDescricao.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jScrollPane7.setViewportView(jEditorPane1);

        jPanelDescricao.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 110));

        jLabelcontacto.setText("Contacto do Vendedor");

        jButtonfavorit.setText("Adicionar aos Favoritos");

        jLabel15.setText("Classificação do Vendedor(0 a 5)");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelpreco2.setText("Preço :");

        jLabelvalor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelvalor.setText("Valor(€€€€)");

        jButtoncomprar.setText("Comprar");

        jButtontrocar.setText("Propor Troca");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelpreco2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtoncomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtontrocar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtontrocar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos vendedor "));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProdutoCompraLayout = new javax.swing.GroupLayout(ProdutoCompra);
        ProdutoCompra.setLayout(ProdutoCompraLayout);
        ProdutoCompraLayout.setHorizontalGroup(
            ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonfavorit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProdutoCompraLayout.setVerticalGroup(
            ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addComponent(jPanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelcontacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonfavorit))
                    .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BodyPrincipal.add(ProdutoCompra, "ProdutoCompra");

        ProdutoEmLeilao.setPreferredSize(new java.awt.Dimension(426, 400));
        ProdutoEmLeilao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImagemLeilao.setBorder(javax.swing.BorderFactory.createTitledBorder("ImagensProduto"));
        jPanelImagemLeilao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("sd");
        jPanelImagemLeilao.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 90));

        ProdutoEmLeilao.add(jPanelImagemLeilao, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 12, 150, 110));

        jPanelDescricaoProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));
        jPanelDescricaoProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("Nome");
        jPanelDescricaoProduto.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, -1));

        jLabel21.setText("Descrição :");
        jPanelDescricaoProduto.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        jPanelDescricaoProduto.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        ProdutoEmLeilao.add(jPanelDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 170));

        jLabelcontacto1.setText("Contacto do Vendedor");
        ProdutoEmLeilao.add(jLabelcontacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 145, -1));

        jLabel22.setText("Classificação do Vendedor(0 a 5)");
        ProdutoEmLeilao.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jButtonfavorit1.setText("Adicionar aos Favoritos");
        ProdutoEmLeilao.add(jButtonfavorit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 30));

        jLabel24.setText("Licitação Atual:");
        ProdutoEmLeilao.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel25.setText("€€€€");
        ProdutoEmLeilao.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel26.setText("Teto de licitação: ");
        ProdutoEmLeilao.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel27.setText("€€€€");
        ProdutoEmLeilao.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel28.setText("Data do Fim do Leilão:");
        ProdutoEmLeilao.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel29.setText("aaaa/mm/dd    hh:mm");
        ProdutoEmLeilao.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 120, -1));

        jTextField5.setText("valorALicitar");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        ProdutoEmLeilao.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 80, 30));

        jButton3.setText("Licitar");
        ProdutoEmLeilao.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        jButton4.setText("Compro Já");
        ProdutoEmLeilao.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 30));

        jButton5.setText("Propor Troca");
        ProdutoEmLeilao.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos do mesmo Vendedor "));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        ProdutoEmLeilao.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 390, 80));

        BodyPrincipal.add(ProdutoEmLeilao, "ProdutoLeilao");

        Vender.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanelAddImagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem"));
        jPanelAddImagem.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jLabelImagemProd);

        jPanelAddImagem.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        JpanelPropriedadesProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));
        JpanelPropriedadesProduto.setMaximumSize(new java.awt.Dimension(195, 370));
        JpanelPropriedadesProduto.setPreferredSize(new java.awt.Dimension(195, 370));

        lnome.setText("Nome produto :");

        jTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeActionPerformed(evt);
            }
        });

        jLdescricao.setText("Descrição:");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jComboBoxCategoria1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<html><strong>Categoria</strong></html>", "Moda", "Tecnologia", "Moveis", "Casa e Jardim", "Lazer", "Desporto", "Imoveis", "Emprego", "Carros", "Motos", "Barcos", "Animais", "Serviços", "Outros" }));
        jComboBoxCategoria1.setToolTipText("");
        jComboBoxCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoria1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelPropriedadesProdutoLayout = new javax.swing.GroupLayout(JpanelPropriedadesProduto);
        JpanelPropriedadesProduto.setLayout(JpanelPropriedadesProdutoLayout);
        JpanelPropriedadesProdutoLayout.setHorizontalGroup(
            JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                .addGroup(JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                        .addComponent(lnome, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                        .addComponent(jComboBoxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLdescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JpanelPropriedadesProdutoLayout.setVerticalGroup(
            JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelPropriedadesProdutoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JpanelPropriedadesProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnome)
                    .addComponent(lnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelpreco.setText("Preço:");

        jButtonvend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ColocarVender.png"))); // NOI18N
        jButtonvend.setText("Colocar à venda");
        jButtonvend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvendActionPerformed(evt);
            }
        });

        jLabelEuro.setText("€");

        jBcimagem.setText("Carregar Imagem");
        jBcimagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcimagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VenderLayout = new javax.swing.GroupLayout(Vender);
        Vender.setLayout(VenderLayout);
        VenderLayout.setHorizontalGroup(
            VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VenderLayout.createSequentialGroup()
                        .addComponent(jButtonvend)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(VenderLayout.createSequentialGroup()
                        .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VenderLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanelAddImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(VenderLayout.createSequentialGroup()
                                .addGap(0, 15, Short.MAX_VALUE)
                                .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(VenderLayout.createSequentialGroup()
                                        .addComponent(jLabelpreco)
                                        .addGap(15, 15, 15)
                                        .addComponent(jTexpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBcimagem))))
                        .addGap(18, 18, 18)
                        .addComponent(JpanelPropriedadesProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                .addContainerGap())
        );
        VenderLayout.setVerticalGroup(
            VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBcimagem)
                .addGap(87, 87, 87)
                .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTexpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelpreco)
                    .addComponent(jLabelEuro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonvend, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(VenderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JpanelPropriedadesProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        BodyPrincipal.add(Vender, "cardVender");

        jPanelPesquisaAvanc.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Avançada"));

        jComboBoxTransacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Venda", "Leilão", " " }));
        jComboBoxTransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTransacaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de Transação :");

        jCheckBoxActivaFiltro.setText("Activar Filtro");
        jCheckBoxActivaFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActivaFiltroActionPerformed(evt);
            }
        });

        jPanelVLeilao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Preço de:");

        jTextField1.setText("0,00");

        jTextField2.setText("0.00");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel30.setText("Até:");

        jLabel31.setText("€");

        jLabel32.setText("€");

        javax.swing.GroupLayout jPanelVLeilaoLayout = new javax.swing.GroupLayout(jPanelVLeilao);
        jPanelVLeilao.setLayout(jPanelVLeilaoLayout);
        jPanelVLeilaoLayout.setHorizontalGroup(
            jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVLeilaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVLeilaoLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVLeilaoLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelVLeilaoLayout.setVerticalGroup(
            jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVLeilaoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelVLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jPanelPesquisaAvancLayout = new javax.swing.GroupLayout(jPanelPesquisaAvanc);
        jPanelPesquisaAvanc.setLayout(jPanelPesquisaAvancLayout);
        jPanelPesquisaAvancLayout.setHorizontalGroup(
            jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaAvancLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesquisaAvancLayout.createSequentialGroup()
                        .addComponent(jCheckBoxActivaFiltro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaAvancLayout.createSequentialGroup()
                        .addGroup(jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaAvancLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTransacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaAvancLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanelVLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanelPesquisaAvancLayout.setVerticalGroup(
            jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaAvancLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaAvancLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxActivaFiltro)
                .addGap(10, 10, 10)
                .addComponent(jPanelVLeilao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPesquisaAvanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DefUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(271, 271, 271)
                    .addComponent(BodyPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addGap(238, 238, 238)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logotipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelPesquisaAvanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(DefUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(BodyPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed
      CardLayout card =(CardLayout) this.BodyPrincipal.getLayout();
      card.show(this.BodyPrincipal,"cardVender");
    }//GEN-LAST:event_jButtonVenderActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void ChavePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChavePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChavePesquisaActionPerformed

    private void BodyPrincipalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_BodyPrincipalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyPrincipalComponentAdded

    private void jComboBoxTransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTransacaoActionPerformed

    }//GEN-LAST:event_jComboBoxTransacaoActionPerformed

    private void jTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeActionPerformed

    private void jButtonKingAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKingAreaActionPerformed
       abreJanelaAreaCliente();
    }//GEN-LAST:event_jButtonKingAreaActionPerformed

    private void jBcimagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcimagemActionPerformed
       abreFileChooser();  
    }//GEN-LAST:event_jBcimagemActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBoxActivaFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActivaFiltroActionPerformed
    pesqAvancEnable();
    }//GEN-LAST:event_jCheckBoxActivaFiltroActionPerformed

    private void jComboBoxCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoria1ActionPerformed

    private void jButtonvendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvendActionPerformed
        // TODO add your handling code here:
//        sys.addProduto(p.getReg(), new Produto(WIDTH, title, imgProduto, title, title));
    }//GEN-LAST:event_jButtonvendActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPrincipal;
    private javax.swing.JTextField ChavePesquisa;
    private javax.swing.JPanel DefUser;
    private javax.swing.JPanel JpanelPropriedadesProduto;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel PanelPesq;
    private javax.swing.JPanel ProdutoCompra;
    private javax.swing.JPanel ProdutoEmLeilao;
    private javax.swing.JPanel Vender;
    private javax.swing.JButton jBcimagem;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonKingArea;
    private javax.swing.JButton jButtonLeiloar;
    private javax.swing.JButton jButtonMenuFavoritos;
    private javax.swing.JButton jButtonPesqAvan;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonResults;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JButton jButtoncomprar;
    private javax.swing.JButton jButtonfavorit;
    private javax.swing.JButton jButtonfavorit1;
    private javax.swing.JButton jButtontrocar;
    private javax.swing.JButton jButtonvend;
    private javax.swing.JCheckBox jCheckBoxActivaFiltro;
    private javax.swing.JComboBox jComboBoxCategoria;
    private javax.swing.JComboBox jComboBoxCategoria1;
    private javax.swing.JComboBox jComboBoxTransacao;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEuro;
    private javax.swing.JLabel jLabelImagemProd;
    private javax.swing.JLabel jLabelLogoTipo;
    private javax.swing.JLabel jLabelPesq;
    private javax.swing.JLabel jLabelcontacto;
    private javax.swing.JLabel jLabelcontacto1;
    private javax.swing.JLabel jLabelpreco;
    private javax.swing.JLabel jLabelpreco2;
    private javax.swing.JLabel jLabelvalor;
    private javax.swing.JLabel jLdescricao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAddImagem;
    private javax.swing.JPanel jPanelDescricao;
    private javax.swing.JPanel jPanelDescricaoProduto;
    private javax.swing.JPanel jPanelImagem;
    private javax.swing.JPanel jPanelImagemLeilao;
    private javax.swing.JPanel jPanelMenuUser;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JPanel jPanelPesquisaAvanc;
    private javax.swing.JPanel jPanelVLeilao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollResultadosPesquisa;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableResultadosPesquisa;
    private javax.swing.JTextField jTexpreco;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTnome;
    private javax.swing.JLabel lnome;
    private javax.swing.JPanel logotipo;
    // End of variables declaration//GEN-END:variables
   
}
