/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;

/**
 *
 * @author Pedro
 */
public class PrincipalBody extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrincipalBody
     */
    public PrincipalBody() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logotipo = new javax.swing.JPanel();
        jLabelLogoTipo = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JPanel();
        jButtonVender = new javax.swing.JButton();
        jButtonLeiloar = new javax.swing.JButton();
        jButtonMenuFavoritos = new javax.swing.JButton();
        jPanelPesquisa = new javax.swing.JPanel();
        jLabelPesq = new javax.swing.JLabel();
        ChavePesquisa = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jButtonPesquisar = new javax.swing.JButton();
        DefUser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelMenuUser = new javax.swing.JPanel();
        jButtonKingArea = new javax.swing.JButton();
        jButtonAjuda = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        BodyPrincipal = new javax.swing.JPanel();
        jPanelpesq = new javax.swing.JPanel();
        jButtonPesqAvan = new javax.swing.JButton();
        jButtonResults = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableResultadosPesquisa = new javax.swing.JTable();
        ProdutoCompra = new javax.swing.JPanel();
        jPanelImagem = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelDescricao = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabelcontacto = new javax.swing.JLabel();
        jButtonfavorit = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelpreco2 = new javax.swing.JLabel();
        jLabelvalor = new javax.swing.JLabel();
        jButtoncomprar = new javax.swing.JButton();
        jButtontrocar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ProdutoEmLeilao = new javax.swing.JPanel();
        jPanelImagemLeilao = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanelDescricaoProduto = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelcontacto1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButtonfavorit1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Vender = new javax.swing.JPanel();
        pcimagem = new javax.swing.JPanel();
        jBcimagem = new javax.swing.JButton();
        nomedescricao = new javax.swing.JPanel();
        lnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLdescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabelpreco = new javax.swing.JLabel();
        jTexpreco = new javax.swing.JTextField();
        jButtonvend = new javax.swing.JButton();

        logotipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelLogoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FinalLog128.png"))); // NOI18N

        javax.swing.GroupLayout logotipoLayout = new javax.swing.GroupLayout(logotipo);
        logotipo.setLayout(logotipoLayout);
        logotipoLayout.setHorizontalGroup(
            logotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logotipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logotipoLayout.setVerticalGroup(
            logotipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logotipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelLogoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        MenuPrincipal.setName("Produtos"); // NOI18N

        jButtonVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ColocarVender.png"))); // NOI18N
        jButtonVender.setText("Vender");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });

        jButtonLeiloar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ColocarEmLeilão.png"))); // NOI18N
        jButtonLeiloar.setText("Leiloar");

        jButtonMenuFavoritos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pedro\\Dropbox\\GitDSS\\DSS\\2-Fase\\DSS\\src\\Imagens\\lixo.png")); // NOI18N
        jButtonMenuFavoritos.setText("Favoritos");

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMenuFavoritos, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jButtonLeiloar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButtonLeiloar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMenuFavoritos)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanelPesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPesq.setText("Pesquisa:");

        ChavePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChavePesquisaActionPerformed(evt);
            }
        });

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categorias", "Item 2", "Item 3", "Item 4" }));

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPesq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChavePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChavePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
        );

        DefUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        DefUser.setName("Definições de Utilizador"); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/kingAvatar.png"))); // NOI18N

        jPanelMenuUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Menu do User ")));

        jButtonKingArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/KingArea.png"))); // NOI18N
        jButtonKingArea.setText("King Area");

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Help.png"))); // NOI18N
        jButtonAjuda.setText("Ajuda          ");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Loginicon.png"))); // NOI18N
        jButtonSair.setText(" Sair            ");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuUserLayout = new javax.swing.GroupLayout(jPanelMenuUser);
        jPanelMenuUser.setLayout(jPanelMenuUserLayout);
        jPanelMenuUserLayout.setHorizontalGroup(
            jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuUserLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKingArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuUserLayout.setVerticalGroup(
            jPanelMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuUserLayout.createSequentialGroup()
                .addComponent(jButtonKingArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DefUserLayout = new javax.swing.GroupLayout(DefUser);
        DefUser.setLayout(DefUserLayout);
        DefUserLayout.setHorizontalGroup(
            DefUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefUserLayout.createSequentialGroup()
                .addComponent(jPanelMenuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        DefUserLayout.setVerticalGroup(
            DefUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMenuUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BodyPrincipal.setPreferredSize(new java.awt.Dimension(400, 400));
        BodyPrincipal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                BodyPrincipalComponentAdded(evt);
            }
        });
        BodyPrincipal.setLayout(new java.awt.CardLayout());

        jPanelpesq.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));
        jPanelpesq.setToolTipText("");
        jPanelpesq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPesqAvan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N
        jButtonPesqAvan.setText("Pesquisa Avançada");
        jPanelpesq.add(jButtonPesqAvan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 170, 30));

        jButtonResults.setText("Mais Resultados");
        jPanelpesq.add(jButtonResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, 30));

        jTableResultadosPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTableResultadosPesquisa);

        jPanelpesq.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, 120));

        BodyPrincipal.add(jPanelpesq, "card7");

        jPanelImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Foto");

        javax.swing.GroupLayout jPanelImagemLayout = new javax.swing.GroupLayout(jPanelImagem);
        jPanelImagem.setLayout(jPanelImagemLayout);
        jPanelImagemLayout.setHorizontalGroup(
            jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelImagemLayout.setVerticalGroup(
            jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDescricao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDescricao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Nome");
        jPanelDescricao.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel13.setText("Descrição :");
        jPanelDescricao.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jScrollPane7.setViewportView(jEditorPane1);

        jPanelDescricao.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 110));

        jLabelcontacto.setText("Contacto do Vendedor");

        jButtonfavorit.setText("Adicionar aos Favoritos");

        jLabel15.setText("Classificação do Vendedor(0 a 5)");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelpreco2.setText("Preço :");

        jLabelvalor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelvalor.setText("Valor(€€€€)");

        jButtoncomprar.setText("Comprar");

        jButtontrocar.setText("Propor Troca");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelpreco2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtoncomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtontrocar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtontrocar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos vendedor "));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProdutoCompraLayout = new javax.swing.GroupLayout(ProdutoCompra);
        ProdutoCompra.setLayout(ProdutoCompraLayout);
        ProdutoCompraLayout.setHorizontalGroup(
            ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonfavorit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        ProdutoCompraLayout.setVerticalGroup(
            ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProdutoCompraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ProdutoCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ProdutoCompraLayout.createSequentialGroup()
                        .addComponent(jPanelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelcontacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonfavorit))
                    .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BodyPrincipal.add(ProdutoCompra, "ProdutoCompra");

        ProdutoEmLeilao.setPreferredSize(new java.awt.Dimension(426, 400));
        ProdutoEmLeilao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImagemLeilao.setBorder(javax.swing.BorderFactory.createTitledBorder("ImagensProduto"));
        jPanelImagemLeilao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("sd");
        jPanelImagemLeilao.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 90));

        ProdutoEmLeilao.add(jPanelImagemLeilao, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 12, 150, 110));

        jPanelDescricaoProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));
        jPanelDescricaoProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("Nome");
        jPanelDescricaoProduto.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, -1));

        jLabel21.setText("Descrição :");
        jPanelDescricaoProduto.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        jPanelDescricaoProduto.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        ProdutoEmLeilao.add(jPanelDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 170));

        jLabelcontacto1.setText("Contacto do Vendedor");
        ProdutoEmLeilao.add(jLabelcontacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 145, -1));

        jLabel22.setText("Classificação do Vendedor(0 a 5)");
        ProdutoEmLeilao.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jButtonfavorit1.setText("Adicionar aos Favoritos");
        ProdutoEmLeilao.add(jButtonfavorit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 30));

        jLabel24.setText("Licitação Atual:");
        ProdutoEmLeilao.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel25.setText("€€€€");
        ProdutoEmLeilao.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel26.setText("Teto de licitação: ");
        ProdutoEmLeilao.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel27.setText("€€€€");
        ProdutoEmLeilao.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel28.setText("Data do Fim do Leilão:");
        ProdutoEmLeilao.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel29.setText("aaaa/mm/dd    hh:mm");
        ProdutoEmLeilao.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 120, -1));

        jTextField5.setText("valorALicitar");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        ProdutoEmLeilao.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 80, 30));

        jButton3.setText("Licitar");
        ProdutoEmLeilao.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        jButton4.setText("Compro Já");
        ProdutoEmLeilao.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 30));

        jButton5.setText("Propor Troca");
        ProdutoEmLeilao.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos do mesmo Vendedor "));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        ProdutoEmLeilao.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 390, 80));

        BodyPrincipal.add(ProdutoEmLeilao, "ProdutoLeilao");

        Vender.setPreferredSize(new java.awt.Dimension(400, 400));

        pcimagem.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBcimagem.setText("Carregar Imagem");

        javax.swing.GroupLayout pcimagemLayout = new javax.swing.GroupLayout(pcimagem);
        pcimagem.setLayout(pcimagemLayout);
        pcimagemLayout.setHorizontalGroup(
            pcimagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBcimagem, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        pcimagemLayout.setVerticalGroup(
            pcimagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pcimagemLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jBcimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nomedescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        nomedescricao.setMaximumSize(new java.awt.Dimension(195, 370));
        nomedescricao.setPreferredSize(new java.awt.Dimension(195, 370));

        lnome.setText("Nome:");

        jTnome.setText("Nome");

        jLdescricao.setText("Descrição:");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        javax.swing.GroupLayout nomedescricaoLayout = new javax.swing.GroupLayout(nomedescricao);
        nomedescricao.setLayout(nomedescricaoLayout);
        nomedescricaoLayout.setHorizontalGroup(
            nomedescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomedescricaoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lnome)
                .addGap(4, 4, 4)
                .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(nomedescricaoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLdescricao))
            .addGroup(nomedescricaoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        nomedescricaoLayout.setVerticalGroup(
            nomedescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomedescricaoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(nomedescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nomedescricaoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lnome))
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLdescricao)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelpreco.setText("Preço:");

        jTexpreco.setText("€€€€€€");

        jButtonvend.setText("Colocar a Vender");

        javax.swing.GroupLayout VenderLayout = new javax.swing.GroupLayout(Vender);
        Vender.setLayout(VenderLayout);
        VenderLayout.setHorizontalGroup(
            VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenderLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pcimagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VenderLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonvend, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(VenderLayout.createSequentialGroup()
                                .addComponent(jLabelpreco)
                                .addGap(9, 9, 9)
                                .addComponent(jTexpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addComponent(nomedescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        VenderLayout.setVerticalGroup(
            VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenderLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(VenderLayout.createSequentialGroup()
                        .addComponent(nomedescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(VenderLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pcimagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VenderLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelpreco))
                            .addComponent(jTexpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonvend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        BodyPrincipal.add(Vender, "cardVender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(DefUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(BodyPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(DefUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logotipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(158, Short.MAX_VALUE)
                    .addComponent(BodyPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed
      CardLayout card =(CardLayout) this.BodyPrincipal.getLayout();
      card.show(this.BodyPrincipal,"cardVender");
    }//GEN-LAST:event_jButtonVenderActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void ChavePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChavePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChavePesquisaActionPerformed

    private void BodyPrincipalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_BodyPrincipalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BodyPrincipalComponentAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPrincipal;
    private javax.swing.JTextField ChavePesquisa;
    private javax.swing.JPanel DefUser;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel ProdutoCompra;
    private javax.swing.JPanel ProdutoEmLeilao;
    private javax.swing.JPanel Vender;
    private javax.swing.JButton jBcimagem;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonKingArea;
    private javax.swing.JButton jButtonLeiloar;
    private javax.swing.JButton jButtonMenuFavoritos;
    private javax.swing.JButton jButtonPesqAvan;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonResults;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JButton jButtoncomprar;
    private javax.swing.JButton jButtonfavorit;
    private javax.swing.JButton jButtonfavorit1;
    private javax.swing.JButton jButtontrocar;
    private javax.swing.JButton jButtonvend;
    private javax.swing.JComboBox jComboBoxCategoria;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogoTipo;
    private javax.swing.JLabel jLabelPesq;
    private javax.swing.JLabel jLabelcontacto;
    private javax.swing.JLabel jLabelcontacto1;
    private javax.swing.JLabel jLabelpreco;
    private javax.swing.JLabel jLabelpreco2;
    private javax.swing.JLabel jLabelvalor;
    private javax.swing.JLabel jLdescricao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDescricao;
    private javax.swing.JPanel jPanelDescricaoProduto;
    private javax.swing.JPanel jPanelImagem;
    private javax.swing.JPanel jPanelImagemLeilao;
    private javax.swing.JPanel jPanelMenuUser;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JPanel jPanelpesq;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableResultadosPesquisa;
    private javax.swing.JTextField jTexpreco;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTnome;
    private javax.swing.JLabel lnome;
    private javax.swing.JPanel logotipo;
    private javax.swing.JPanel nomedescricao;
    private javax.swing.JPanel pcimagem;
    // End of variables declaration//GEN-END:variables
}
