/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Paxaxa
 */
public class sugestoes extends javax.swing.JPanel {

    /**
     * Creates new form sugestoes
     */
    public sugestoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSugests = new javax.swing.JPanel();
        jScrollPaneSugestoes = new javax.swing.JScrollPane();
        jTableSugestoes = new javax.swing.JTable();
        jToggleButtonVerProduto = new javax.swing.JToggleButton();

        jPanelSugests.setBorder(javax.swing.BorderFactory.createTitledBorder("Sugestões"));

        jTableSugestoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSugestoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSugestoesMouseClicked(evt);
            }
        });
        jScrollPaneSugestoes.setViewportView(jTableSugestoes);

        jToggleButtonVerProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/file.png"))); // NOI18N
        jToggleButtonVerProduto.setText("Ver Produto");
        jToggleButtonVerProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVerProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSugestsLayout = new javax.swing.GroupLayout(jPanelSugests);
        jPanelSugests.setLayout(jPanelSugestsLayout);
        jPanelSugestsLayout.setHorizontalGroup(
            jPanelSugestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSugestsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonVerProduto)
                .addContainerGap())
            .addGroup(jPanelSugestsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneSugestoes, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelSugestsLayout.setVerticalGroup(
            jPanelSugestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSugestsLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPaneSugestoes, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonVerProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSugests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanelSugests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonVerProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVerProdutoActionPerformed
        //Se for leilão carLicitar, compra , cardLeiout compara
        CardLayout card =(CardLayout) this.BodyPrincipal.getLayout();
        card.show(this.BodyPrincipal,"cardLicitar");        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonVerProdutoActionPerformed

    private void jTableSugestoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSugestoesMouseClicked
         if (evt.getClickCount()==1)  
            System.out.println("Nada Feito");  
        if (evt.getClickCount()==2)  
            System.out.println("Is True, duplo Clique");  
    }//GEN-LAST:event_jTableSugestoesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelSugests;
    private javax.swing.JScrollPane jScrollPaneSugestoes;
    private javax.swing.JTable jTableSugestoes;
    private javax.swing.JToggleButton jToggleButtonVerProduto;
    // End of variables declaration//GEN-END:variables
}
