/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dss;

/**
 *
 * @author Paxaxa
 */
public class PesquisaAva extends javax.swing.JPanel {

    /**
     * Creates new form PesquisaAva
     */
    public PesquisaAva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisaAvan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesquisaAvan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pesquisaAvanFocusGained(evt);
            }
        });
        pesquisaAvan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pesquisa:");
        pesquisaAvan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 30));

        jTextField1.setText("Nome do Produto");
        pesquisaAvan.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 160, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categorias", "Item 2", "Item 3", "Item 4" }));
        pesquisaAvan.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 90, 30));

        jButton1.setText("OK");
        pesquisaAvan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 60, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        pesquisaAvan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 250, 50));

        jLabel5.setText("Mais resultados");
        pesquisaAvan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLabel2.setText("Preço de :");
        pesquisaAvan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jTextField2.setText("€€€€€€");
        pesquisaAvan.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 60, 20));

        jLabel6.setText("até:");
        pesquisaAvan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jTextField3.setText("€€€€€€€");
        pesquisaAvan.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel7.setText("Tipo de Transação :");
        pesquisaAvan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Venda", "Leilão", " " }));
        pesquisaAvan.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, 20));

        jLabel8.setText("Data :");
        pesquisaAvan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jTextField4.setText("aaaa/mm/dd");
        pesquisaAvan.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, -1));

        add(pesquisaAvan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 380, 348));
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisaAvanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisaAvanFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaAvanFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel pesquisaAvan;
    // End of variables declaration//GEN-END:variables
}
